# Basic Android settings
android.useAndroidX=true
android.enableJetifier=true

# Build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.workers.max=4

# Kotlin style
kotlin.code.style=official

# Java Home
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio1\\jbr
